services:
  dockge:
    image: louislam/dockge:1
    container_name: dockge
    restart: unless-stopped
    ports:
      - 5001:5001 # 用户可自定义
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker/dockge/data:/app/data # 用户可自定义
      - /opt/docker/dockge/stacks:/opt/stacks # 用户可自定义
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks
# networks: # 通常不需要指定 bridge network
#  default:
#    external:
#      name: bridge
